Updated link to rust-mdns repo (for compatibility to kernel version prior 3.9)
Linked the rust-mdns Repo to my own modified fork on Github. 
The original rust-mdns repo from user plietar tries to use the Kernel Option SO_REUSEPORT which was first introduced in Kernel Version 3.9. Starting libspotify on kernel version prior 3.9 using the discovery feature (no User/Pass required while starting Librespot) might run into an error like this:
"thread 'main' panicked at 'calledResult::unwrap()on anErrvalue: Error { repr: Os { code: 92, message: "Protocol not 
available" } }', /checkout/src/libcore/result.rs:860 note: Run withRUST_BACKTRACE=1 for a backtrace."
My modified fork of rust-mdns does not use the SO_REUSEPORT call (see https://github.com/librespot-org/librespot/wiki/Compile-librespot-for-kernel-prior-3.9).